16 lines (16 sloc)  460 Bytes

my_new_project:  # your profile name from dbt_project.yml
  target: dev    
  # your development environment
  outputs:  
    dev:
      type: bigquery
      method: oauth
      project: thriftshop-ment360-demo
      # name of the project in BigQuery
      dataset: dbt_thriftshopment360
      location: australia-southeast1
      # your dataset for development (usually your name)
      threads: 1
      timeout_seconds: 300
      priority: interactive
      retries: 1